#!/bin/bash

COMMIT_MSG_FILE=$1
MSG_TO_PREPEND=$(git branch --show-current)

# remove branch name at the start of the commit message if it already exists (for eg: when the commit message is being amended)
sed -i -e "s/^$MSG_TO_PREPEND://"  $COMMIT_MSG_FILE
COMMIT_FILE_CONTENTS=$(cat $COMMIT_MSG_FILE)

# Include any branches for which you wish to disable this script
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop)
fi

if [[ $MSG_TO_PREPEND == $BRANCHES_TO_SKIP ]];then
    exit 0
fi


echo "$MSG_TO_PREPEND: $COMMIT_FILE_CONTENTS" > $COMMIT_MSG_FILE
